### PR TITLE
changed pp to use pprint only if obj is not string

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose
For strings, `BaseSolver.pp()` should call `print` if `obj` is a string, otherwise call `pprint`.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Review by sseraj — COMMENTED** [review]
Does using `pprint` for strings break anything? It seemed to work fine for ADflow.
We might also want to consider using a more descriptive name than `pp`, especially if it's not actually using `pprint` in all cases.

**Comment by nwu63** [comment]
> Does using `pprint` for strings break anything? It seemed to work fine for ADflow.

Doesn't break anything but it does not render the string properly. See:
```
>>> pprint('abc')
'abc'
>>> pprint('\nabc')
'\nabc'
```
vs.
```
>>> print('abc')
abc
>>> print('\nabc')

abc
```

> We might also want to consider using a more descriptive name than `pp`, especially if it's not actually using `pprint` in all cases.

Yeah, I think we've also used stuff like `root_print` before but I still favour `pp` for the conciseness. I think if we document it well then it _should_ be okay. IMO the main purpose here is to print on the root proc rather than any pretty formatting (which I would consider a secondary goal), but then by that logic the function name is not very good...

**Review by marcomangano — COMMENTED** [review]
I like the conciseness of `pp`, but I am not sure how much this can be ambiguous... maybe something more explicit like `root_print` might be the way to go.
What about `rt_pp` as a compromise? :)

Anyway, this function will only be used by developers, so we can check if it is misused during the PR reviews.

**Comment by nwu63** [comment]
I still prefer `self.pp` to be honest, and with most editors if you hover your mouse over the text it should display the docstrings so there should be no excuses for using it incorrectly. I also can't really think of a way where you would misuse `self.pp` and introduce bugs by misunderstanding what it's for.

**Review by marcomangano — APPROVED** [review]

**Review by sseraj — APPROVED** [review]

**Pull request merged**
