### PR TITLE
Adding a simple parser to parse string format

### PR DESCRIPTION
**Pull request by eirikurj**
## Purpose
This PR adds a very simple parser to parse string formats. This parser can be used to extract information for different str formats, such as width and sign, for printing to stdout. 

## Expected time until merged
No rush

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Checklist

- [x] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [x] I have run unit and regression tests which pass locally with my changes
- [x] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Review by A-CGray — APPROVED** [review]
Wow, looks good, great work!

**Review by marcomangano — APPROVED** [review]
Very nice

**Comment by sseraj** [comment]
> For some reason the tests haven't even started (they are not listed in the pipeline queue), do you have a way to rerun them with your privileges @eirikurj ?

I just manually started the tests

**Comment by A-CGray** [comment]
Good to go @sseraj ?

**Pull request merged**
