### PR TITLE
Preparation for PyPI release

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose
This PR changes several things in preparation for PyPI release
- Updated `setup.py` and `README`
- incremented patch version

Publishing `baseclasses` on PyPI has several benefits
- pyOptSparse can switch to using these base classes to avoid code duplication, while still allowing dependencies to be installed automatically by pip without cloning/building from source
- building documentation on RTD (particularly for the options) will require baseclasses to be present. Previously with API documentation, autodoc was able to mock baseclasses since it only needed to access the docstrings, but now with the options documentation a class instance must be initialized which requires baseclasses to access the `defaultOptions` class attribute.

Note that I have changed the PyPI package name to `mdolab-baseclasses` since `baseclasses` itself feels too vague and I didn't want to reserve that on PyPI for this package. I chose this name based on precedence with other published packages, such as [django-baseclasses](https://pypi.org/project/django-baseclasses/). This will _not_ impact usage of this package since you will still be able to write `import baseclasses`, but the `install_requires` option in `setup.py` of the various downstream packages will have to be updated for the changes to propagate.

Once this is merged, I will make a new tag and Travis _should_ be able to just publish this directly on PyPI.

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing
No code changes

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by sseraj** [comment]
Should we open simultaneous PRs for the downstream `install_requires` changes? Or are you planning on directly committing those once this is merged?

**Comment by nwu63** [comment]
> Should we open simultaneous PRs for the downstream `install_requires` changes? Or are you planning on directly committing those once this is merged?

That's a good point, build bot will fail once this is merged in. If you want to make PRs that would be nice (but Travis will probably fail). Otherwise I can also just manually push which would probably be faster.

**Comment by sseraj** [comment]
If Travis is going to fail, then committing directly is probably better. Otherwise an admin will have to merge all the PRs anyway.

**Review by sseraj — APPROVED** [review]

**Review by eirikurj — APPROVED** [review]
Looks good. Let me know, and I can also assist in manually modifying or merging PRs in the downstream repos.

**Comment by marcomangano** [comment]
@nwu63 @eirikurj Just wanted to report one of the incompatibilities to be fixed downstream, in this case for `pyAeroStructure`:
```
File "as_run.py", line 73, in <module>
    AS(asp)
  File "/home/mmangano/miniconda3/lib/python3.8/site-packages/pyaerostructure/pyAeroStruct.py", line 311, in __call__
    for Iter in range(nIter):
TypeError: 'list' object cannot be interpreted as an integer
```
This is from the AS analysis script from the tutorial, looks like it's reading the default `nMDIter` option list instead of getting the provided option. `baseclasses v1.2.3` works fine of course.

**Pull request merged**
